### ISSUE TITLE
Alterar arquivos em base de extensão

### ISSUE THREAD

**Issue by lissarubi** [lissatransborda/transchange#4]
É interessante a possibilidade dos arquivos serem alterados em base de sua extenção, como `**.md`, modificando diversos arquivos de uma única vez, e se adequando a cada repositório da pessoa.

**Comment by trystan2k** [comment]
Olá @lissatransborda,

Aqui você quer dizer que deve procurar todos os arquivos .md em todos os diretórios (e subdiretórios) ?

Porque tirando os subdiretórios, eu acredito que isso já possa ser possível. Se quando perguntado que arquivo você quer alterar, você colocar *.md, irá alterar todos os arquivos .md que tenha na raiz do repositório.

Agora se tiver que incluir também os subs (o que seria uma boa ideia mesmo), aí já teria que ser implementado mesmo.

**Comment by PauloGoncalvesBH** [comment]
@trystan2k se já for possível acho que seria interessante adicionar exemplos sobre como fazer isso.

**Comment by lissarubi** [comment]
> Olá @lissatransborda,
> 
> Aqui você quer dizer que deve procurar todos os arquivos .md em todos os diretórios (e subdiretórios) ?
> 
> Porque tirando os subdiretórios, eu acredito que isso já possa ser possível. Se quando perguntado que arquivo você quer alterar, você colocar *.md, irá alterar todos os arquivos .md que tenha na raiz do repositório.
> 
> Agora se tiver que incluir também os subs (o que seria uma boa ideia mesmo), aí já teria que ser implementado mesmo.

Alterar os arquivos dentro dos subdiretórios também.

Por enquanto não encontrei alguma opção dentro da lib do sed para alterar arquivos pela extensão, você achou algo relacionado à isso?

**Comment by trystan2k** [comment]
> 
> Alterar os arquivos dentro dos subdiretórios também.
> 
> Por enquanto não encontrei alguma opção dentro da lib do sed para alterar arquivos pela extensão, você achou algo relacionado à isso?

Para alterar arquivos por extensão, é só colocar como nome do arquivo `*.extensão`, por exemplo *.md, porém só vai aí alterar os arquivos que tenham essa extensão no diretório raiz.

Para alterar em subdiretórios, só com o sed não dá. Teria que fazer um find e aí iterar sobre o resultado chamando sed para cada um.

Vou ver se consigo fazer e abro uma PR se der certo.

**Comment by trystan2k** [comment]
Olá @lissatransborda ,

Criei a PR para adicionar busca de arquivos por extensão e por subdiretórios. Para isso adicionei uma nova pergunta onde se pode dizer se quer procurar em todos os subs ou não (sendo o default por deixar com a mesma funcionalidade de antes).

Adicionei no Readme exemplos de como se pode buscar por extensão (*.md) e também por wildcards (*.config.* - encontraria, por exemplo, `babel.config.js` ou `babel.config.json`)

Qualquer comentário ou dúvida, é só avisar!
